
import { Product, Category, StoreConfig, Customer } from './types';

export const INITIAL_STORE_CONFIG: StoreConfig = {
  nameEn: "",
  nameAr: "",
  vatNumber: "",
  crNumber: "",
  vatRate: 0.15,
  phone: "",
  address: "",
  currency: "SAR",
  loyaltyRate: 1, // 1 point per SAR
  footerMessage: "",
  lowStockThreshold: 5,
  setupComplete: false,
  logoDataUrl: ""
};

export const INITIAL_PRODUCTS: Product[] = [];

export const INITIAL_CUSTOMERS: Customer[] = [];

export const TRANSLATIONS = {
  en: {
    pos: 'POS',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    customers: 'Customers',
    expenses: 'Expenses',
    orders: 'Orders',
    settings: 'Settings',
    search: 'Search...',
    scanBarcode: 'Scan Barcode (Enter)',
    addToCart: 'Add to Cart',
    total: 'Total',
    currency: 'SAR',
    subtotal: 'Subtotal',
    vat: 'VAT (15%)',
    discount: 'Discount',
    payCash: 'Cash',
    payCard: 'Card',
    payCredit: 'Credit',
    holdCart: 'Hold Cart',
    recallCart: 'Recall Cart',
    clearCart: 'Clear Cart',
    receipt: 'Tax Invoice',
    refund: 'Refund',
    thankYou: 'Thank you for shopping with us!',
    vatNo: 'VAT Number',
    phone: 'Phone',
    date: 'Date',
    items: 'Items',
    price: 'Selling Price',
    qty: 'Qty',
    customer: 'Customer',
    balance: 'Balance',
    payDebt: 'Pay Debt',
    save: 'Save',
    cancel: 'Cancel',
    productNameEn: 'Product Name (EN)',
    productNameAr: 'Product Name (AR)',
    category: 'Category',
    stock: 'Stock',
    stockLow: 'Low Stock',
    barcode: 'Barcode',
    cost: 'Purchasing Price',
    expiryDate: 'Expiry Date',
    addNewProduct: 'Add New Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    dailySales: 'Daily Sales',
    monthlySales: 'Monthly Sales',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    expired: 'Expired',
    expiringSoon: 'Expiring Soon',
    print: 'Print',
    whatsapp: 'WhatsApp',
    openShift: 'Open Shift',
    closeShift: 'Close Shift',
    startCash: 'Starting Cash',
    endCash: 'Ending Cash',
    expectedCash: 'Expected Cash',
    difference: 'Difference',
    expenseDescription: 'Description',
    amount: 'Amount',
    addExpense: 'Add Expense',
    selectCustomer: 'Select Customer',
    newCustomer: 'New Customer',
    zReport: 'Z-Report',
    totalWithVat: 'Total (inc. VAT)',
    recentTransactions: 'Recent Transactions',
    noItems: 'Cart is empty',
    miscItem: 'Custom Item',
    addNote: 'Add Note',
    note: 'Note',
    storeSettings: 'Store Settings',
    dangerZone: 'Danger Zone',
    resetData: 'Reset All Data',
    exportCsv: 'Export CSV',
    misc: 'Misc'
  },
  ar: {
    pos: 'نقطة البيع',
    dashboard: 'لوحة التحكم',
    inventory: 'المخزون',
    customers: 'العملاء',
    expenses: 'المصاريف',
    orders: 'الطلبات',
    settings: 'الإعدادات',
    search: 'بحث...',
    scanBarcode: 'مسح الباركود (Enter)',
    addToCart: 'إضافة للسلة',
    total: 'الإجمالي',
    currency: 'ر.س',
    subtotal: 'المجموع الفرعي',
    vat: 'الضريبة (15%)',
    discount: 'خصم',
    payCash: 'نقد',
    payCard: 'بطاقة',
    payCredit: 'آجل',
    holdCart: 'تعليق السلة',
    recallCart: 'استرجاع سلة',
    clearCart: 'مسح السلة',
    receipt: 'فاتورة ضريبية',
    refund: 'استرجاع',
    thankYou: 'شكراً لتسوقكم معنا!',
    vatNo: 'الرقم الضريبي',
    phone: 'الجوال',
    date: 'التاريخ',
    items: 'الأصناف',
    price: 'سعر البيع',
    qty: 'الكمية',
    customer: 'العميل',
    balance: 'الرصيد',
    payDebt: 'سداد دين',
    save: 'حفظ',
    cancel: 'إلغاء',
    productNameEn: 'اسم المنتج (EN)',
    productNameAr: 'اسم المنتج (عربي)',
    category: 'التصنيف',
    stock: 'المخزون',
    stockLow: 'منخفض المخزون',
    barcode: 'الباركود',
    cost: 'سعر الشراء',
    expiryDate: 'تاريخ الانتهاء',
    addNewProduct: 'إضافة منتج جديد',
    editProduct: 'تعديل منتج',
    deleteProduct: 'حذف منتج',
    dailySales: 'مبيعات اليوم',
    monthlySales: 'مبيعات الشهر',
    lowStock: 'منخفض المخزون',
    outOfStock: 'نفذت الكمية',
    expired: 'منتهية الصلاحية',
    expiringSoon: 'قرب الانتهاء',
    print: 'طباعة',
    whatsapp: 'واتساب',
    openShift: 'فتح وردية',
    closeShift: 'إغلاق وردية',
    startCash: 'النقد في البداية',
    endCash: 'النقد عند الإغلاق',
    expectedCash: 'النقد المتوقع',
    difference: 'الفرق',
    expenseDescription: 'الوصف',
    amount: 'المبلغ',
    addExpense: 'إضافة مصروف',
    selectCustomer: 'اختر عميل',
    newCustomer: 'عميل جديد',
    zReport: 'تقرير Z',
    totalWithVat: 'الإجمالي مع الضريبة',
    recentTransactions: 'آخر العمليات',
    noItems: 'السلة فارغة',
    miscItem: 'منتج مخصص',
    addNote: 'إضافة ملاحظة',
    note: 'ملاحظة',
    storeSettings: 'إعدادات المتجر',
    dangerZone: 'منطقة الخطر',
    resetData: 'حذف جميع البيانات',
    exportCsv: 'تصدير CSV',
    misc: 'مفرقات'
  }
};
